### ISSUE TITLE
Install issues on Mac OS X

### ISSUE THREAD

**Issue by josephhardinee** [utvisionlab/mixest#8] opened 2018-02-23 03:37 UTC
I'm running into an issue with the mixest install script. I'm running it on OS X 10.12 with Matlab R2016b. 

```
>> install_mixest
Installing the MixEst toolbox...
Adding MixEst folders to search path...
[Done]
Compiling mex files...
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
MEX completed successfully.
[Done]

MixEst has been successfully installed.
You can use "Set Path" -> "Save" from MATLAB menus to save the added paths permanently.

Building search database for the documentation (Optional Step)...
Error using builddocsearchdb (line 25)
The specified directory does not exist.

Error in install_mixest (line 28)
builddocsearchdb(fullfile(toolbox_root_path, 'doc', 'public'))
 ```

**Comment by mrmashal** [comment] 2018-02-23 04:24
Looks like the main steps of compiling the C source files and updating the paths is done correctly. The last step (`builddocsearchdb`) is not crucial and only enables searching the documentations from inside Matlab.

I guess the issue is that you're not using a [released version](https://github.com/utvisionlab/mixest/releases) where we prepare the docs using Jekyll in the `doc/public` folder. Maybe our releases is somewhat outdated now. I'll try to draft a new one ASAP.

**Comment by mrmashal** [comment] 2018-02-23 05:20
Release [v1.3.0](https://github.com/utvisionlab/mixest/releases/tag/v1.3.0) is available for download. I'll close this issue for now. Feel free to re-open if there are any more problems.

**Closed as completed by mrmashal** 2018-02-23 05:20 UTC
